ray-x/go.nvim

README.md
lua/go.lua
lua/go/install.lua
lua/go/utils.lua

While using the plugins I experienced a few reliability issues, so here a pull request to fix them :)
1. Installation: 
-  `go get` is used to install the binaries, however, `go get` will be deprecated for binary installations, so I changed it to `go install`.  
- The link for gofumpt has been changed, as it didn't work anymore.
- Binaries were only looked for in `$GOPATH/bin`, while on some systems commands such as `gofmt` are not installed in that location my default. Therefore I changed binary detection to `which <bin>`, to check for systemwide binaries.
- Added `$PATH` instructions to the README.md
2. Formatting:
- the function to detect if code had been changed was inverted. 
- by default, the format function reads from file instead of from the current buffer. As you are working in …

Increase reliability

---

lua/go.lua
lua/go/dap.lua

- fix dap.stop deprecated: https://github.com/mfussenegger/nvim-dap/commit/96d552eea64ec696406e19f1ca29000c4112a8b9
- fix DapStop / DapRerun not working

fix: deprecated dap.stop

---

lua/go/format.lua

With sync formatting, the function can be used in BufWritePre without the buffer ending up modified the save.

Make formatting sync during import

---

lua/go/dap.lua

Running `GoDebug` on `main()` will fail if there are multiple files in `package main` since the other files won't be compiled along with the target file.

Support multiple files on GoDebug

---

README.md
lua/go/gotest.lua

There were missing whitespaces once CMD was built.
This way white spaces are ensured.
Thanks again for this plugin

fix: build tags was missing space

---

README.md

I fixed the link to redirect toward the provided config example in the README as opposed to a file within the repository.

fix typo and broken link

---

lua/go/gotest.lua

The default package parameter for TestFun is not needed because this
function is meant to target the current file only. Using the default
package parameter increased run time of time function drastically.

fix: test fun defaults

---

lua/go/gotest.lua

Test file function wasn't working anymore. It didn't find functions to
test even though the sed found them.
Problem was in the escaping the pipe sign inside go test command.

fix: test file function

---

README.md
lua/go.lua
lua/go/gotests.lua

GoAddTest, GoAddExpTest and GoAddAllTest affected. Previously they weren't work with templates (go_nvim_test_template
variable) because file paths should be last argument to gotests. Also removed different handling of stdout/stderr because seems that gotests doesn't use stderr or produce any exit code except zero (that probably OK, but not useful for go.nvim).

Fix gotests integration

---

lua/go/alternate.lua

The original logic fails if you have go in your path, like: `/Code/mygoproject/myfile.go` because the split will have more than two elements.

Handle literal "go" in path for GoAlt command

---

lua/go/runner.lua

`GoGet` and `GoMod` opens up a new split and move the cursor there. If the cursor isn't moved back to the *.go buffer before the command completes, `utils.restart` will try to spawn gopls in the terminal split buffer, which results in gopls failed to restart properly.
This is a quickfix though, since error will still occur if for example we run `GoGet` on nvim-tree buffer without moving the cursor back to the go file

Return cursor to previous cursor position when using `GoGet` and `GoMod`

---

README.md
doc/go.txt
lua/go.lua

Clarify the doc of setup option `test_runner`
1. Remove duplicate item `richgo`.
2. Change `go test` to `go` for accuracy.

doc: clarify test_runner option

---

lua/go/lsp.lua

- Removes `telescope_code_actions()` function.
- Sets associated keybinding to `vim.lsp.buf.code_action`
First of all, love the plugin, thanks for creating such a great tool.
I am submitting this PR as I recently lost code actions functionality with go.nvim and was presented with:
A bit of googling later I found out that it appears the `code actions` builtin has been removed from telescope. More on this [here](https://github.com/nvim-telescope/telescope.nvim/pull/1866) and [here](https://github.com/nvim-telescope/telescope.nvim/issues/1470#issuecomment-1106707726). 
For now using the `vim.lsp.buf.code_action` command seems to be the way to go. In order to get some nice UI component integration back  [telescope-ui-select](https://github.com/nvim-telescope/telescope-ui-select.nvim) and …

fix(code_actions): Remove now deprecated telescope_code_actions()

---

README.md

In the Debug section Command table `GoBreakToggle` was mentioned twice, I just removed the duplicate

fix(docs): fix command typo and duplicate

---

lua/go/dap.lua

Calling `c` repeatedly caused the state of stdout stderr and handle to drift, resulting in the closure of nil.
Example error:
```
...share/nvim/site/pack/packer/start/go.nvim/lua/go/dap.lua:352: attempt to index upvalue 'stdout' (a nil value)
stack traceback:
...share/nvim/site/pack/packer/start/go.nvim/lua/go/dap.lua:352: in function <...share/nvim/site/pack/packer/start/go.nvim/lua/go/dap.lua:341>
[C]: in function 'handler'
/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:434: in function 'match_preds'
/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:519: in function 'iter'
/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:287: in function 'fn'
/usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:194: in function 'for_each_tree' …
```

fix(dap): don't close empty stdout stderr handle Add nil check to closure of stdout stderr handle

---

lua/go/term.lua

Float terminal command is tranformed to string using table.concat before
used. This allow us to use neovim buff option to unite quoting.

Cmd is tranformed to string before pushed to term

---

lua/go/lsp.lua

Fixes #162.
Providing a function for the lsp_on_client_start option wouldn't ever get executed previously. Also, if it would, there inside was infinite recursion. Both issues are fixed with this PR.

fix lsp_on_client_start option

---

lua/go/coverage.lua

GoCoverage was failing when looping over the coverage and because `utils.notify` does not exist anymore

Fix: GoCoverage

---

lua/go/inlay.lua

Changes uneven spacing in virtual text in parameter hint from:
`( ctx,  X1,  Y1,  X2,  Y2,  duration)`
to 
`(ctx, X1, Y1, X2, Y2, duration)`
this is an embarassingly small commit.

remove leading space on hint args

---

lua/go/format.lua
lua/go/lsp.lua

When saving file while using auto saving (from README).
```
vim.api.nvim_exec([[ autocmd BufWritePre *.go :silent! lua require('go.format').goimport() ]], false)
```
The code is formatted, but not saved. (Formatting is executed after the file is saved)
Thie PR causes that goimports to be synchronous. (depending on lsp_fmt_async)

synchronous goimports

---

lua/go/dap.lua

I think When somebody is debugging a test function, it means the real one test function name, not all the funcs start with the same prefix.

fix: use strict test function name while debugging

---

lua/go/gotest.lua

dlv does provide a flag for passing build tags, although it is diferent
than the build tag flag for the go command line utility. This commit
adds that syntax to pass flags to dlv as specified.

Pass build tags when running tests with dlv

---

lua/go/gotest.lua

```shell
$ uname -mrsv
Darwin 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64
```
```shell
$ nvim --version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
```
```shell
$ cd ~/.local/share/nvim/site/pack/packer/start/go.nvim && git log
commit 6ef00998e2003db399df8251da1c30fd20eada43 (HEAD -> master, origin/master, origin/HEAD)
Author: ray-x <rayx.cn@gmail.com>
Date:   Fri Sep 2 23:52:34 2022 +1000
keymap for range code action
```
```shell
$ pwd
/Users/ruifeng/Documents/Obsidian-code/Go-learning/语言基础/005-learn-go-with-tests/003-hello-world
```
```
$ ls
go.mod  main.go main_test.go
```
```shell
$ cat main.go
package main
func Get5() int {
return 5
}
func main() {
}
```
```shell
$ cat main_test.go
package main
import …
```

fix test_func

---

README.md
lua/go/coverage.lua

The current GoCoverage command runs tests on the entire repository, which, when running on a project that takes e.g. a minute to complete testing, is quite slow. Vscode-go and Vim-go, when running their equivalent commands, will run tests on the current buffer's package, thus returning visual results _much_ faster. (In my use case, some packages may take milliseconds to test while others may take several seconds, but never the full minute that running this command as-is would require.)
The PR adds a `-p` option to the coverage command that will get the package for the current buffer and only run tests for it, greatly increasing iteration time. There's only one caveat with which I require help - Vim seems to give out `Missed option for -p` even though after logging this error everything …

Add an option for single package coverage.

---

lua/go/inlay.lua

fix bug when using inlay hints.
Since the buf_request is deferred, the current buffer may have changed during the 500ms delay.

fix: use saved bufnr when retrieving inlay hints.

---

lua/go/asyncmake.lua
lua/tests/go_test_spec.lua

Hi @ray-x , thanks for this commit https://github.com/ray-x/go.nvim/commit/e9d1c6c02159965f9f1bbd5699ddbdb9a4f92088. for this issue https://github.com/ray-x/go.nvim/issues/229, 
however, the previous  would create insert the args after the ```-run``` resulted in error.
this PR is trying to fix that. and is my first time writing lua, do let me know if is ok
i.e 
``` require("go.gotest").test_func("-a", "mock=true")``` would result in
``` go test -tags=tag1,tag2 -v -run -args mock=true '^TestXXXX$' ./XXX'```
expected is 
``` go test -tags=tag1,tag2 -v -run '^TestXXXX$' ./XXX -args mock=true '```

fix(gotest): wrong order of test binary args

---

lua/go/lsp.lua

hihi go.nivm team. I found GoGenReturn is very useful but for method this command not support, So this MR is support for method
Run GoGenReturn 
`client.DeleteWithTimeout()` -> `	*clientv3.DeleteResponse, err := client.DeleteWithTimeout()`

feat: support generate return for method

---

lua/go/coverage.lua

HL group for uncovered code is called `goCoverageUncovered` but code used `goCoverageUncover`.

fix: fix used hl group name

---

lua/go/coverage.lua

remove_all was defined as local but then referenced once as local and once as method in M

fix: wrong method scope

---

after/queries/go/injections.scm
after/queries/go/locals.scm

If this comment is not present it will overwrite all existing queries with the content of the respective file.
Also move files from queries/go -> after/queries/go to ensure they are loaded after e.g. nvim-treesitter queries.
This is especially visible with `locals.scm` as for me it did not longer auto-highlight other occurrences of the same variable until I added `;; extends` at the top.

fix: latest treesitter expects ;; extends

---

lua/go/tags.lua

`GoAddTag` was throwing an error due to an `=` in the place of `==`

fix: tags add comparison typo

---

lua/go/utils.lua

I believe this might have been committed on accident.
In addition, there seems to be a separate issue. I get this output on startup:
`WARN: find failed find ./ -type f -name /home/ray/go/src/github/sample/app/driver.go{ "FIND: Invalid switch\r" }`
Which leads me to believe somewhere the script is shelling out to `find`.
I'm on Windows where `find.exe` is not the POSIX variant, so any function that depends on it will likely fail.

utils.lua remove debugging expression

---

lua/go/null_ls.lua

This fixes the following error:
[null-ls] failed to run generator: 
```
...are/nvim/site/pack/packer/opt/go.nvim/lua/go/null_ls.lua:46: attempt to concatenate local 'package' (a nil value)
```

fix nil error

---

lua/go/null_ls.lua

```
Error executing luv callback:
vim/_editor.lua:0: E5560: nvim_echo must not be called in a lua loop callback
stack traceback:
[C]: in function 'nvim_echo'
vim/_editor.lua: in function 'notify'
...are/nvim/site/pack/packer/opt/go.nvim/lua/go/null_ls.lua:164: in function 'check_exit_code'
...m/site/pack/packer/opt/null-ls.nvim/lua/null-ls/loop.lua:122: in function <...m/site/pack/packer/opt/null-ls.nvim/lua/null-ls/loop.lua:101>
```

fix E5560 wrap vim api calls inside luv loop

---

lua/go/gotests.lua

In gotests, the `template` and `template_dir` parameters are two independent parameters. 
You can use 
`gotests -i -template testify -all xxxx`
or 
`gotests -i -template_dir yourtemplatedirpath -all xxxx` 
These two are not strongly bound (since someone might have simply created a few tmpl templates to meet their own needs).
I have noticed that in go.nvim, there is a dependency relationship between these two parameters. So I made some adjustments.
This will not affect the current template users, but it can help those who have only set the template_dir, as it was not previously effective when only configuring `gotests_template_dir`.

fix: make the template and template dir parameters independent.

---

lua/go/gopls.lua

Fixes related issue:
https://github.com/ray-x/go.nvim/issues/323

issue-323 fix: check valid tags before overwriting gopls buildFlags

---

lua/go/install.lua
lua/go/utils.lua
lua/tests/go_tags_spec.lua

Tools will be installed in the appropriated directory when [goenv](https://github.com/syndbg/goenv) manages GOPATH.
I tried to make it work on Mac, Linux (Ubuntu), ~and Windows but I have no way of testing it on Windows~ 😅 
goenv doesn't seem to be supported on Windows.

Ensure correct tools installation in goenv mode

---

lua/go/snips.lua

vim.treesitter.set_query is deprecated. Using vim.treesitter.query.set instead.

Migrate to new Treesitter query API

---

ftdetect/filetype.vim

The documentation @ https://github.com/ray-x/go.nvim/blob/8a0498ee48a26f928b1dc1c02fb3d84d648a1c63/doc/go.txt#L90 indicates that there is html support for *.gohtml files but this doesn't seem to be the case.
It can be currently overridden in your NeoVim settings by running the following Lua code after setup:
```lua
vim.api.nvim_command('au BufRead,BufNewFile *.gohtml set filetype=gohtmltmpl')
```

adding support for *.gohtml files as per documentation.

---

README.md
doc/go.txt
lua/go.lua

This pull request changes the default character for the prefix in a diagnostic virtual text line to the same one used in neovim by default ([see here](https://github.com/neovim/neovim/blob/8c9dab3e0d788d44c8a2fee83a6193f5955c814e/runtime/lua/vim/diagnostic.lua#L1065))
The existing character ("") used to work for me but has recently gone missing and does not render.
If this change makes sense perhaps it would also make sense to change `parameter_hints_prefix` as it
(for me) similarly does not render. If you agree I can make the change.
Thanks again for the lovely plug in ❤️ .

change default `lsp_diag_virtual_text` prefix to nvim default

---

README.md
doc/go.txt
lua/go.lua
lua/go/gotestsum.lua
lua/go/package.lua

Replace using [nerdfix](https://github.com/loichyan/nerdfix).
Nerdfont >= 3.0.0 dropped class name `nf-mdi-*`, replacing with new class name `nf-md-*`.
The new class name exists since nerdfont 2.3.0 so user with nerdfont >= 2.3.0 installed should be fine.
Refer https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0

fix(ui): replace obsolete nerd fonts from ui

---

ftdetect/filetype.vim

Docs say that `*.gotext` should be recognized as `gotexttmpl` but that is not the case.
I also changed `*.tmpl` to `gotexttmpl` since that is how I use it - not certain if that would be acceptable to everyone though.

fix: correct filetype assignments

---

after/queries/go/injections.scm

Import paths like 'database/sql' are string literals and activate tree-sitter language injection for SQL. Adding a `#not-has-ancestor` predicate for `import_declaration` prevents this.
Example:

Disable ts injections in import strings

---

README.md
doc/go.txt
lua/go.lua

This PR corrects the key used to configure the virtual text spacing for diagnostics.
As per [Neovim's documentation](https://neovim.io/doc/user/diagnostic.html#diagnostic-api), the appropriate key for controlling the virtual text's spacing is `spacing`. However, the current configuration incorrectly uses `space`.
**Before**:
```lua
virtual_text = { space = 0, prefix = '■' },
```
**After**:
```lua
virtual_text = { spacing = 0, prefix = '■' },
```
It's worth noting that this change may not have a noticeable impact on functionality. This is because a `nil` spacing value might be interpreted similarly to a spacing value of 0.

Fix Incorrect Key for Virtual Text Spacing in Diagnostics Configuration

---

lua/go/asyncmake.lua
lua/go/coverage.lua
lua/go/health.lua

not all golang env specific variables are injected into vim.env, so check their presence based on go env instead

fixup: check for env variables based on go env

---

lua/go/gotest.lua
lua/tests/fixtures/coverage/branch_test.go
lua/tests/go_test_spec.lua

```
go test -v ./domain/transforming/transformers/internal/denom -run="^\QTest_Shorten\E$"/"^\Qinterval [1, 500] - step 1\E$" 
```
that's how it is supposed to be able to run any sub-test.

go sub tests names needs to be regex quoted

---

README.md

Fixing markdown syntax errors in readme document

fix(doc): modify mismatched code block

---

lua/go/gotest.lua
lua/tests/go_test_spec.lua

When providing custom arguments (`:GoTest-n -a -test.timeout=5s`), the resultant command will be:
`go test <package> -args -test.timeout=5s -run=<exp>`
Since `-run` is after `-args`, the `-test.` prefix is required to be properly detected. According to `go help testflags`, all test commands are recognized with this prefix.

fix: prefix -run in GoTestXXX with '-test'

---

lua/go/inlay.lua

Change the calls to inlay_hint.enable to arrange the parameters in the expected way.
Fixes #451 
this is the error this PR addresses:
```
vim.lsp.inlay_hint.enable(bufnr:number, enable:boolean) is deprecated, use vim.lsp.inlay_hint.enable(enable:boolean, filter:table) instead. :help
deprecated
Feature was removed in Nvim 0.10-dev
```

Fixes #451 inlay hint api change

---

lua/go.lua

a recent commit utilizes `vim.islist` which is only available in neovim v0.10 which is still new and not necessarily widely available across all package managers or used yet. It's probably a good idea to at least support the previous version along with the current version.

fix: add back compatibility with neovim v0.9

---

lua/go/codelens.lua
lua/go/lsp.lua

The behavior of `vim.lsp.codelens.refresh()` had been changed in https://github.com/neovim/neovim/pull/27253 to refresh all open buffers.
This changes the function calls to specify the current buffer to maintain the old behavior.
Fixes https://github.com/ray-x/go.nvim/issues/472.

fix: limit codelens refresh to current buffer

---

.gitignore

Thank you for these superb code action additions for golang! I use them regularly.
I use native vim package management in combination with git submodules. Every time I run `:helptags ALL` the only plugin I use that shows erroneous submodule files is go.nvim because a `doc/tags` file has been generated.
I think it is harmless to add this to the ignore list and you generally don't check these in as most plugin managers generate them for you.

Ignore `doc/tags`

---

lua/go/list.lua
lua/go/package.lua

Partially fixes #484
Right now, module-aware mode is consistently disabled in `:GoBuild` completions due to setting `GO111MODULE=off`, so completion does not work in the large majority of Go projects[^1].
Alternatively, the plugin could switch to using `GO111MODULE=auto` but, in my opinion, these global Go environment variables are better off remaining under the user's control.
This PR does _not_ address the duplication of completed entries, described in the referenced issue, since it is a whole separate problem from the one being addressed here.
[^1]: Since Go 1.16, module-aware mode is [enabled by default](https://go.dev/ref/mod#mod-commands). That version was released on 2021-02-16, which is over 3 years ago at the time of submitting this PR.

fix: GoBuild cmd completion is not module-compatible

---

doc/go.txt

A space was missing, and I think a few extra word making it clearer that the file needs to be adapted and is a configuration file will help.

Improve command description

---

README.md
lua/go.lua
lua/go/lsp.lua

This adds the option to disable the semantic token highlights coming from gopls. This is a popular option for people who are used to not having these highlights and prefer the default (eg. Treesitter) ones.

Add option to disable semantic highlights

---

Makefile
lua/go/gotest.lua
lua/tests/go_test_spec.lua

The float term is not working when running tests with the `-s` arg, here we check if the float term is enabled when selecting the tests, and run only the selected on the float term.

Enabling select test to run on floatterm

---

lua/go/dap.lua

The only way to trigger the .vscode/launch.json dropdown list was to be on a `func main` function, which is unlikely when you're trying to debug from a large Go project. go.nvim was assuming that `GoDebug` with no params, would always be on a `Test*` function, which was then causing the `elif cfg_exist` to never reach: https://github.com/gcollura/go.nvim/blob/18f782221a6a72840e9dcf4f5b13cbd5f2967c1d/lua/go/dap.lua?plain=1#L557
This PR checks a little more strictly that the user doesn't want to trigger a debug run on a "test", and it doesn't try to override the option passed by the user. For example it would set `optarg['t'] = true` even when another flag was passed.

fix forcing test godebug on `GoDebug` without params

---

README.md
lua/go.lua
lua/go/dap.lua

DAP suggests passing an `enrich_config` function to the adapter configuration to allow "hydrating" the launch.json configuration in case it contains an `envFile`, eg. https://github.com/mfussenegger/nvim-dap/discussions/548#discussioncomment-8778225
It can also be useful to expose this function given that `dap.adapters.go` gets overwritten by `go.nvim`. https://github.com/mfussenegger/nvim-dap/blob/8517126e9323e346f6a99b3b594c5a940b914dcd/doc/dap.txt#L199-L220
If nil, the enrich_config function is ignored, so we're going to default to that: https://github.com/mfussenegger/nvim-dap/blob/8517126e9323e346f6a99b3b594c5a940b914dcd/lua/dap.lua#L458
The motivation for me is that calling `GoEnv` depending on which launch configuration I select is a bit cumbersome, especially when different …

Add dap_enrich_config to pass enrich_config to dap adapter config

---

lua/go/gopls.lua

Problem:
Docs suggest settting diagnostic to false to set elsewhere in your config. This leads to an runtime error accessing it here
Solution:
Add a check to ensure that the diagnostic configuration is not false before accessing its properties.

fix(gopls): handle nil diagnostic config

---

queries/go/injections.scm

After some recent update sql injection stopped working for me. Removing offsets solved the issue, so probably `raw_string_literal_content` now returns the string content without the qoutes/backticks.

fix sql injection

---

README.md
lua/go.lua
lua/go/commands.lua

In case the Vim command created by `go.nvim` clashes with another plugin's Vim command, there is no _great_ way today to work around that, it seems.
Add ability to opt _out_ of command creation for specific `go.nvim` commands, or remap to a different command.
Example config:
```lua
opts = {
remap_commands = {
GoFmt = "GoFormat", -- remaps :GoFmt to :GoFormat 
GoDoc = false  -- disables go.nvim's :GoFmt command creation
},
}
```
If you would rather see a simple `disable_commands` option, I added an alternative PR for that in #547

feat: option to remap (or disable) vim command creation

---

queries/go/injections.scm

Before, when using master only sql works:
After, json works as well:
Side note, I only tested this with neovim 0.10.4
Resolves https://github.com/ray-x/go.nvim/issues/551

fix(injections): make json injections work in nvim 0.10.0

---

lua/go/dap.lua

When you manually stop a DAP session w/ `GoDebug -s` the GDB-like keybinds are unmapped and the original keybinds are restored; however, when a program exits naturally you have to make an explicit call to unmap (via another `GoDebug -s` call for example) to restore the keybinds.
This pull request includes changes to `dap.lua` that use dap event listeners to bind/unbind keymaps. I've tested with starting, restarting, manual exit and natural program completion/exit. On restart the maps are unmapped and remapped but it doesn't seem to be too heavy of an operation.
My primary concern is that these changes will have unintended side-effects that those more familiar w/ the code base and DAP might see. I'm also unsure of the [-r] argument and if I handled the code changes around that correctly. …

use dap events to bind/unbind keymaps

---

lua/go/health.lua

Resolves #567
checks that there is a space either before the first number or the 'v' so that go1.X.X is not matched

fix: match golangci-lint versions that don't start with 'v'

---

lua/go/lsp.lua

looks like in the latest updated the LSP name was accidentally changed to `gppls`, which now causes me to have 2 LSPs attached `gopls` and `gppls`
```
:LspInfo
- gppls (id: 2)
- gopls (id: 3)
```

bugfix: correct type for gopls

---

README.md

Update setup instructions for lazy.nvim users. Let's lazy run the setup and uses lazy plugin's `init` function instead of putting stuff in the init.lua file.

fix: lazy.nvim setup instructions

---

README.md

Update lazy.nvim setup as discussed in #572

fix: use config instead of init for lazy.nvim

---

README.md

Simple fix to a typo (missing comma) in the example `lazy.nvim` configuration.

fix: missing comma in lazy.nvim config in README.md

---

queries/go/highlights.scm

Here's something fun, It de-emphasizes if err != nil blocks. I started using this for my own config. Feel free to close this.

feat(highlights.scm): make if err != nil blocks less emphasized

---

README.md
doc/go.txt
lua/go/commands.lua

Fixing typo on `Govulncheck` to `GoVulnCheck`.

docs: fix typo on Govulnckeck

---

lua/go/rename.lua

This PR fixes a UX issue where we're being prompted twice for the new identifier name when performing a rename operation with an active LSP client.
**Problem**
The current implementation shows a prompt to get the new identifier name, and then checks if an LSP client is available. If a client exists, it calls lsprename() which shows its own prompt, resulting in being asked twice for the same input.
**Solution**
Check for the LSP client availability before prompting. This ensures we only see one prompt:
_If LSP client is available_: Use lsprename() directly (with its built-in prompt)
_If no LSP client_: Show prompt and proceed with gorename fallback
_Tests for go_fillstruct were already failing before my changes_
Fixes #586

fix: resolve double prompt and non-functional gorename fallback
