- lua/go/format.lua
- lua/go/iferr.lua
- lua/go/reftool.lua
- lua/go/rename.lua
- lua/go/tags.lua
- lua/go/utils.lua
Remove extra empty line in vim's job. To fix #5
> Fix format error on macOS

- lua/go/format.lua
- lua/go/iferr.lua
- lua/go/reftool.lua
- lua/go/rename.lua
- lua/go/tags.lua
I'm sorry for that. I was confused by 'util' and 'utils' and make some typos. Now I fixed it. I tried these changed features, it works as before.
> fix require('go.util') error

- lua/go/dap.lua
> using dlv no output fix

- README.md
- doc/go.txt
- lua/go.lua
Claorify lsp_on_attach in the docs.
> Make lsp_on_attach nil by default

- README.md
The current vimrc sample has a lua comment in the viml part.
> Fix sample vimrc comment

- README.md
- doc/go.txt
- lua/go.lua
> Set dap_debug_keymap to true by default

- README.md
- doc/go.txt
- lua/go.lua
- lua/go/term.lua
Added GoTermClose command to close the floating term.
Closes #118
> feat: added command to close floating term

- README.md
- lua/go/tags.lua
Also clarify `tag_transform` documentation in README for more clarity. I don't even know why i use `true` in `tag_transform` value 😕 
Should fix #120
> Fix tags when using `tag_transform`

- README.md
- doc/go.txt
- lua/go.lua
- lua/go/gotest.lua
- samplevimrc.vim
Toggle to turn on/off verbose test output.
> feat: verbose tests toggle

- README.md
- lua/go.lua
- lua/go/gotests.lua
I wanted to use the gotests template parameters and it didn't work so I did some digging and it looks like there's a bug.
This should fix the bug plus (hopefully):
- better naming/comment for the parameters
- small formatting fixes
- Update README
> fix gotests template parameters

- README.md
see https://github.com/williamboman/nvim-lsp-installer/pull/685
> fix nvim-lsp-installer path moved to core module

- README.md
- doc/go.txt
- lua/go.lua
- lua/go/package.lua
- lua/go/ts/go.lua
- lua/go/ts/utils.lua
- lua/go/utils.lua
This is a new feature.
It not just another sidebar.
It shows all public symbols inside a go package with side panel.
> [Feature]Package info side panel

- lua/go.lua
- lua/go/asyncmake.lua
- lua/go/env.lua
- fix: append check if val is nil Add check to see if value is empty. And don't add to path if already in path.
- feat: auto run main module in floating term Add check to see if floating term, to auto run main file
fix #146
> Fix empty string and GoRun -F main module

- lua/go/dap.lua
- lua/go/keybind.lua
> [Breaking] Change keymap api from nvim_set_keymap to vim.keymap.set

- lua/go/format.lua
GoFmt was failing because utils.notify does not exist anymore
> replace utils.notify by utils.warn

- lua/go/dap.lua
- lua/go/package.lua
GoPkgOutline, should reset pkg_info data before rerender.
> fix: GoPkgOutline, should reset pkg_info data before rerender

- README.md
Based on reading this: https://sharksforarms.dev/posts/neovim-rust/#whats-next
> Specify nvim_create_autocmd in a few places in README

- lua/go.lua
> fix spelling mistakes

- lua/go/dap.lua
when i debugging go file, will be open repl twice, one is the dapui layout config, and another is above code opened.
> fix:opened double repl

- doc/go.txt
> Fix typo in go.txt

- lua/go/ts/nodes.lua
fix: https://github.com/nvim-treesitter/nvim-treesitter/pull/4300
> fix: rename ts_utils.get_node_range -> vim.treesitter.get_node_range

- lua/go/inlay.lua
local var line is a integer not string
> fix:fix can't show inlay in currentline setting

- lua/go/gotest.lua
> fix:go unit test flag "-run" not "-r"

- README.md
- after/queries/go/injections.scm
- after/queries/go/locals.scm
- selene.toml
Hello, I'm a treesitter maintainer for nvim-ts and a bunch of ts grammars, I use this plugin to enrich my (admittedly sparse) go development. I noticed the queries are a bit expensive and not as optimized as they could be for the end user, so I tidied it up and made some changes. Note that `#match?` is quite expensive and `#lua-match?` is much better.
Thanks,
Amaan
> feat: improve queries

- lua/go/health.lua
@ray-x I think you forgot to use the `start` function so quick fix for it!
> fix: deprecated health.report_start function

- lua/go/lsp.lua
It's stopping my editor on every save
> Remove debugging print statement

- after/queries/go/injections.scm
Reverts ray-x/go.nvim#371
Failed neovim 0.9.x
> Revert "Disable ts injections in import strings"

- README.md
> fix(docs): various rendering issues

- lua/go/gopls.lua
> fix:`diagnostic` config may be a false

- playground/README.md
Just fix the typo in the playground README.
> Update playground README

- doc/go.txt
> doc: fix inaccurate description of :GoBuild cmd

- after/queries/go/injections.scm
> Fix injeciton for sql and json

- lua/go/gopls.lua
> Fix lsp hints when disable `lsp_inlay_hints`

- lua/go/lsp_diag.lua
> bugfix: check diagnostic type before using
